tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "tazjin/kontemplate", "https://github.com/tazjin/kontemplate"
brew "awscli"
brew "cfssl"
brew "go"
brew "dep"
brew "git"
brew "git-crypt"
brew "kubernetes-cli"
brew "kops"
brew "mongodb", restart_service: true
brew "pipenv"
brew "pyenv"
brew "rabbitmq", restart_service: true
brew "redis", restart_service: true
brew "tmux"
brew "tree"
brew "wget"
brew "zsh"
brew "tazjin/kontemplate/kontemplate"
cask "alfred"
cask "amethyst"
cask "docker"
cask "firefox"
cask "font-dejavu-sans"
cask "font-dejavu-sans-mono-for-powerline"
cask "font-source-code-pro"
cask "google-cloud-sdk"
cask "gpg-suite"
cask "iterm2"
cask "keybase"
cask "logitech-options"
cask "robo-3t"
cask "slack"
cask "spotify"
cask "tunnelblick"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "zoomus"
